# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: . . .
subtitle: brilliant ideas loading ...  
author: Nikos Bosse 
language: en
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://nikosbosse.com       # Note: don't forget to modify the CNAME file to your url
root: /
# permalink: :year/:month/:day/:title/
permalink: :title/
permalink_defaults:

#Custom Setting Start

# Site settings
SEOTitle: Nikos Bosse
  # email: nikosbosse
description: "Personal website of Nikos Bosse"
keyword: "Nikos Bosse"
header-img: img/header_img/home-bg-1-dark.jpg
signature: false #show signature
signature-img: img/signature/dusign.png

# SNS settings
github_username: nikosbosse
twitter_username: nikosbosse
linkedin_username: nikosbosse
  #facebook_username:  Gang Du
  # zhi<F12>hu_username: dusignr

# Build settings
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`

# Analytics settings
# Baidu Analytics
# ba_track_id: 4cc1f2d8f3067386cc5cdb626a202900
# Google Analytics
#ga_track_id: 'UA-XXXXXXXX-X'          # Format: UA-xxxxxx-xx
#ga_domain: yoursite

# Sidebar settings
sidebar: true                      # whether or not using Sidebar.
  # sidebar-about-description: "Welcome to my personal website!"
  # sidebar-avatar: img/ironman-draw.png      # use absolute URL, seeing it's used in both `/` and `/about/`
widgets:
- search
# - featured-tags
- short-about
  # - visitor
- recent-posts
- archive
  # - category

## Search
search:
  enable: true
  path: search.xml
  field: post
  content: true

# widget behavior
## Archive
archive_type: 'monthly'
show_count: true


## Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value


## Friends
friends: [
    {
        title: "Nikos's Blog",
        href: "https://nikosbosse.com"
    },{
        title: "Nikos's Github",
        href: "https://github.com/nikosbosse"
    }
]

math:
  enable: true
  engine: mathjax

#Custom Setting End

# Directory
source_dir: source
public_dir: public
  # tag_dir: tags
archive_dir: archives
  # category_dir: categories
photography_dir: photography
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
# new_post_name: :year-:month-:day-:title.md # File name of new posts
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: true # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:
home_posts_tag: true # show posts tags

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: archives

archive_generator:
  per_page: 10
  yearly: true
  monthly: true
  daily: false
  
# Markdown-it config
## Docs: https://github.com/celsomiranda/hexo-renderer-markdown-it/wiki
markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: true
    linkify: true
    typographer: true
    quotes: '“”‘’'
  
# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: snail

#sitemap
sitemap:
  path: sitemap.xml
## Baidusitemap
baidusitemap:
path: baidusitemap.xml

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo:
      github:
      coding:
  branch: master

## share
share: false

# Comment
## This comment system is gitment
## gitment url: https://github.com/imsun/gitment
comment:
  gitment:
    enable: false
    owner:
    repo:
    client_id:
    client_secret:
  livere:
    enable: false
  disqus:
    enable: false
    username:

## music
### netease; qqkg;
### if your `library` is `qqkg`, please set `music` as the song url
# music:
#  enable: true
#  library: netease
#  music: https://kg.qq.com/node/play?s=7deFpz7Z26Jmv7di&g_f=share_html

# Tip
tip:
  enable: false
  copyright: This is copyright.
  content: false

# Background effects
## If there is no effect after modification, please empty the cache and try again.
## ⚠️ The following special effects will take up a lot of cpu resorces, please open it carefully.
bg_effects:
  enable: true
  line:
    enable: false
    color: 129,200,61
    pointColor: 129,200,61
    opacity: 0.7
    zIndex: -9
    count: 99
  mouse_click:
    enable: false
    content: '"🌱","just do it","🍀"'
    color: '"rgb(121,93,179)"
          ,"rgb(76,180,231)"
          ,"rgb(184,90,154)"'
  wave:
    enable: true

# Color Theme
## light , dark or star
## If you set the value of the `color_theme` to `dark`, set the value of the `highlight_theme` to `night` in `/theme/snail/config.yml`
## `mouse_control` is only valid for star themes
color_theme: light
mouse_control: false

# Visitor statistics
visitor:
  enable: false
  type:

# Chinese Blog
chinese_blog:
  enable: false
  url: YOUR_CHINESE_BLOG_URL
